name: GitHub Package

on:
  release:
    types: [created]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Post Checkout
        uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 20
          registry-url: https://npm.pkg.github.com/
          scope: '@erffy'
      - name: Setup Yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 20
      - name: Install Dependencies
        run: yarn install

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Post Checkout
        uses: actions/checkout@master
      - name: Setup .npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN_GITHUB }}" >> $HOME/.npmrc
      - name: Install TypeScript & Prettier
        run: npm i -g typescript prettier
      - name: Build
        run: yarn run build
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_GITHUB }}
      - name: Remove Build
        run: rm -rf src
