name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 20

      - name: Setup Yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install

  publish:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@master

      - name: Setup Node
        uses: actions/setup-node@master
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org/
          
      - name: Setup Yarn
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 20

      - name: Setup TypeScript
        run: npm i -g typescript
        
      - name: Install dependencies
        run: yarn install
        
      - name: Build
        run: yarn run build
        
      - name: Publish
        run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Remove Build
        run: rm -rf src
