name: Node Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Node
        uses: actions/setup-node@master
        with:
          node-version: 20

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@master
        
      - name: Node
        uses: actions/setup-node@master
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      - name: Prepare Required Dependencies
        run: npm install --global yarn typescript tsc-alias

      - name: Install Dependencies
        run: yarn install
        
      - name: Build
        run: npm run build
        
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Remove Build
        run: npm run build:delete